### ISSUE TITLE
PIL version?

### ISSUE THREAD

**Issue by LeonHodgesAustin** [mikepound/mazesolving#11]
I think i have a different version of PIL than the one used in this project. 
Specifically mine does not have the .width property on Image, instead it has the .size property.

changing the code to accommodate this is trivial, but I would like to contribute with out introducing breaking changes.

the version i have is 1.1.7 of python 2.7 from here:
http://www.pythonware.com/products/pil/

output that lead me to this conclusion:
D:\projects\mazesolving>python solve.py -m breadthfirst examples/tiny.png out.png
Loading Image
Creating Maze
Traceback (most recent call last):
  File "solve.py", line 90, in <module>
    main()
  File "solve.py", line 87, in main
    solve(sf, args.method, args.input_file, args.output_file)
  File "solve.py", line 19, in solve
    maze = Maze(im)
  File "D:\projects\mazesolving\mazes2.py", line 15, in __init__
    width = im.width
  File "C:\Python27\Lib\site-packages\PIL\Image.py", line 512, in __getattr__
    raise AttributeError(name)
AttributeError: width

D:\projects\mazesolving>python
Python 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:19:22) [MSC v.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
->>> from PIL import Image
->>> im = Image.open(examples/tiny.png)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'examples' is not defined
->>> im = Image.open("examples/tiny.png")
->>> dir(im)
['_Image__transformer', '_PngImageFile__idat', '__doc__', '__getattr__', '__init__', '__module__', '__repr__', '_copy', '_dump', '_expand', '_makeself', '_new', '_open', 'category', 'convert', 'copy', 'crop', 'decoderconfig', 'decodermaxblock', 'draft', 'filename', 'filter', 'format', 'format_description', 'fp', 'fromstring', 'getbands', 'getbbox', 'getcolors', 'getdata', 'getextrema', 'getim', 'getpalette', 'getpixel', 'getprojection', 'histogram', 'im', 'info', 'load', 'load_end', 'load_prepare', 'load_read', 'mode', 'offset', 'palette', 'paste', 'png', 'point', 'putalpha', 'putdata', 'putpalette', 'putpixel', 'quantize', 'readonly', 'resize', 'rotate', 'save', 'seek', 'show', 'size', 'split', 'tell', 'text', 'thumbnail', 'tile', 'tobitmap', 'tostring', 'transform', 'transpose', 'verify']
->>> im.size
(10, 10)

**Comment by mikepound** [comment]
Hi, thanks for pointing this out. I've altered the maze code to point correctly at size, odd that width and height weren't always there! Let me know if you have any issues with the update, I can't remember where I refer to the width and height of the image.
