### ISSUE TITLE
Issue with parser.parse_args()

### ISSUE THREAD

**Issue by applemonster** [mikepound/mazesolving#12]
Hi, 

I am having problems running this code on my own computer. I get the follwoing error;

`usage: solve.py [-h] [-m [{breadthfirst, depthfirst, dijkstra, astar, leftturn}]] input_file output_file
solve.py: error: the following arguments are required: input_file, output_file`

What do I need to do to solve this?

Thanks!

**Comment by mikepound** [comment]
Hi, yes the command line is altered a little from the video. You now supply the input parameters (like maze in, image out) on the command line. For example, in Windows it might be something like:

python solve.py -m depthfirst .\examples\perfect2k.png .\examples\perfect2k.solved.png

You supply a solver using -m, then you supply the input maze, and a name for the output file.

**Comment by applemonster** [comment]
Perfect! Thanks for the reply!

**Comment by oskstr** [comment]
@mikepound I'd suggest you create some examples for how to use to program. Since it's slightly different from the video. Maybe something like:
## Examples
Solve the maze perfect2k.png with a depth-first search and output it as perfect2k.solved.png.
### Linux and macOS
```bash
python solve.py -m depthfirst ./examples/perfect2k.png ./examples/perfect2k.solved.png
```
### Windows
```
python solve.py -m depthfirst .\examples\perfect2k.png .\examples\perfect2k.solved.png
```

**Comment by Roel1988** [comment]
@oskstr I'd suggest you create some examples in the README for mike, so he can use this to clarify his program to the community. Many hands make light work. @mikepound and @applemonster txs for the clear answer. I love Dijkstra's & A*-algorithm. Nice way also to use heap for efficiency :-). Gr Roel
